# Generated by Django 4.1.2 on 2022-10-15 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usadba_app', '0002_groundtype_ripeningperiods_seedscategories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tomatoseeds',
            name='image',
            field=models.ImageField(null=True, upload_to='.\\../static/img/tomato_product_img'),
        ),
    ]
