# Generated by Django 4.1.2 on 2022-10-16 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usadba_app', '0003_tomatoseeds_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tomatoseeds',
            name='ripe_form',
        ),
        migrations.AlterField(
            model_name='tomatoseeds',
            name='image',
            field=models.ImageField(null=True, upload_to='.\\../static/img/seeds/tomato'),
        ),
    ]
