# Generated by Django 4.1.2 on 2022-10-16 17:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usadba_app', '0004_remove_tomatoseeds_ripe_form_alter_tomatoseeds_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tomatoseeds',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usadba_app.seedscategories'),
        ),
        migrations.AddField(
            model_name='tomatoseeds',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tomatoseeds',
            name='name',
            field=models.CharField(default='DEFAULT NAME12345', max_length=255),
        ),
        migrations.AddField(
            model_name='tomatoseeds',
            name='price',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='tomatoseeds',
            name='ripe_color',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='tomatoseeds',
            name='ripe_form',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tomatoseeds',
            name='ripe_weight_grams',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tomatoseeds',
            name='ripening_period',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usadba_app.ripeningperiods'),
        ),
        migrations.AddField(
            model_name='tomatoseeds',
            name='yield_kg_div_m2',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
