# Generated by Django 4.1.2 on 2022-10-16 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usadba_app', '0005_tomatoseeds_category_tomatoseeds_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tomatoseeds',
            name='description',
        ),
        migrations.RemoveField(
            model_name='tomatoseeds',
            name='name',
        ),
        migrations.RemoveField(
            model_name='tomatoseeds',
            name='price',
        ),
    ]
