# Generated by Django 4.1.2 on 2022-10-16 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usadba_app', '0007_remove_tomatoseeds_category_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TomatoSeeds',
        ),
    ]
