# Generated by Django 4.1.2 on 2022-10-16 17:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usadba_app', '0008_delete_tomatoseeds'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='DEFAULT NAME12345', max_length=255)),
                ('description', models.CharField(max_length=500, null=True)),
                ('price', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='TomatoSeeds',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usadba_app.product')),
                ('ripe_color', models.CharField(max_length=30, null=True)),
                ('ripe_form', models.CharField(max_length=50, null=True)),
                ('ripe_weight_grams', models.IntegerField(null=True)),
                ('yield_kg_div_m2', models.CharField(max_length=15, null=True)),
                ('image', models.ImageField(null=True, upload_to='.\\../static/img/seeds/tomato')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usadba_app.seedscategories')),
                ('ground_growing_conditions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usadba_app.groundtype')),
                ('ripening_period', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usadba_app.ripeningperiods')),
                ('type_of_plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usadba_app.tomatotypeofplant')),
            ],
            options={
                'db_table': 'tomato_seeds',
            },
            bases=('usadba_app.product',),
        ),
    ]
