# Generated by Django 4.1.2 on 2022-10-19 12:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usadba_app', '0009_product_tomatoseeds'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleSeeds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='DEFAULT NAME12345', max_length=255)),
                ('description', models.CharField(max_length=500, null=True)),
                ('price', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('ripe_color', models.CharField(max_length=30, null=True)),
                ('ripe_form', models.CharField(max_length=50, null=True)),
                ('ripe_weight_grams', models.IntegerField(null=True)),
                ('yield_kg_div_m2', models.CharField(max_length=15, null=True)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usadba_app.seedscategories')),
                ('ripening_period', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usadba_app.ripeningperiods')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='tomatoseeds',
            name='category',
        ),
        migrations.RemoveField(
            model_name='tomatoseeds',
            name='ground_growing_conditions',
        ),
        migrations.RemoveField(
            model_name='tomatoseeds',
            name='product_ptr',
        ),
        migrations.RemoveField(
            model_name='tomatoseeds',
            name='ripening_period',
        ),
        migrations.RemoveField(
            model_name='tomatoseeds',
            name='type_of_plant',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='TomatoSeeds',
        ),
    ]
