# Generated by Django 4.1.2 on 2022-10-19 12:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usadba_app', '0013_tomatoseeds_category_tomatoseeds_ripe_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tomatoseeds',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tomatoseeds',
            name='name',
            field=models.CharField(default='DEFAULT NAME12345', max_length=255),
        ),
        migrations.AddField(
            model_name='tomatoseeds',
            name='price',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
