# Generated by Django 4.1.2 on 2022-10-19 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usadba_app', '0014_tomatoseeds_description_tomatoseeds_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tomatoseeds',
            old_name='name',
            new_name='title',
        ),
    ]
