# Generated by Django 4.1.2 on 2022-10-24 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usadba_app', '0015_rename_name_tomatoseeds_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='image',
            field=models.ImageField(null=True, upload_to='.\\./static/img/opinion'),
        ),
        migrations.AlterField(
            model_name='tomatoseeds',
            name='image',
            field=models.ImageField(null=True, upload_to='.\\../static/img/product_img/tomato'),
        ),
    ]
