# Generated by Django 4.1.2 on 2022-10-24 13:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usadba_app', '0016_alter_opinion_image_alter_tomatoseeds_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinion',
            name='rate',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
