# Generated by Django 4.1.2 on 2022-11-05 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usadba_app', '0020_delete_cart_delete_cartandproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tomatoseeds',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_img/TomatoSeeds'),
        ),
    ]
