# Generated by Django 4.1.2 on 2022-11-05 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usadba_app', '0021_alter_tomatoseeds_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='image',
            field=models.ImageField(null=True, upload_to='.\\../media/opinion'),
        ),
    ]
