# Generated by Django 4.1.2 on 2022-11-05 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usadba_app', '0022_alter_opinion_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='image',
            field=models.ImageField(null=True, upload_to='.\\opinion'),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
